const euro=n=>'€'+Math.abs(n).toLocaleString('en-US');
const signed=n=>(n<0?'−':'')+euro(n);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=s=>s.replace(/COGS|PPE|AR|AP/g,m=>m.toLowerCase()).replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()).replace(/\b(cogs|ppe|ar|ap)\b/g,m=>m.toUpperCase());
const evidenceCodes={};
function sourceUrl(s){let file=s.replace(/^03\//,'');return '/evidence/03%20CASE%20FILES%20-%20Open%20and%20Investigate/'+encodeURIComponent(file)}
function evidenceText(list){return (list||[]).map(s=>{let e=Object.entries(evidenceCodes).find(([,v])=>v===s);return e?`<a href="${sourceUrl(s)}" title="${esc(s)}" target="_blank" rel="noopener">${e[0]}</a>`:esc(s)}).join(', ')}
function renderHome(data){
 const bs=data.statements.balanceSheet,pl=data.statements.profitAndLoss;
 document.querySelector('#metrics').innerHTML=[['Revenue',pl.revenue,'Recognized delivery'],['Profit',pl.profitBeforeTax,'Proposed, subject to stock review'],['Cash',bs.cash,'Bank confirmed'],['Net assets',bs.equity,'Assets less liabilities']].map(([name,value,note])=>`<div class="metric"><span>${name}</span><strong>${euro(value)}</strong><small>${note}</small></div>`).join('');
 const statementNames={profitAndLoss:'Profit & loss',cashFlow:'Direct cash flow',balanceSheet:'Balance sheet'};
 document.querySelector('#statements').innerHTML=Object.entries(data.statements).map(([key,rows])=>`<article class="statement"><h3>${statementNames[key]}</h3>${Object.entries(rows).map(([label,value])=>`<div class="row ${['profitBeforeTax','closingCash','liabilitiesAndEquity'].includes(label)?'total':''}"><span>${title(label)}</span><span>${signed(value)}</span></div>`).join('')}</article>`).join('');
 document.querySelector('#schedules').innerHTML=Object.entries(data.schedules).map(([name,rows])=>`<article class="schedule"><h3>${title(name)}</h3>${Object.entries(rows).map(([label,value])=>`<div class="row"><span>${title(label)}</span><span>${signed(value)}</span></div>`).join('')}</article>`).join('');
 document.querySelector('#reconciliations').innerHTML=data.reconciliations.map(r=>`<div class="recon ${r.difference?'warning':''}"><strong>${esc(r.name)} ${r.difference?'· unresolved':'· reconciled'}</strong><p>${esc(r.calculation)}</p></div>`).join('');
 const uncertainties=`<div class="section-head uncertainty-head"><div><p class="eyebrow">Outstanding questions</p><h2>Uncertainties</h2></div></div><div class="uncertainties">${data.uncertainties.map(u=>`<article><strong>${esc(u.issue)}</strong><p>${esc(u.primary)}</p>${u.alternative?`<p><b>Alternative:</b> ${esc(u.alternative)}</p>`:''}${u.status?`<small>${esc(u.status)}</small>`:''}</article>`).join('')}</div>`;
 document.querySelector('#reconciliations').insertAdjacentHTML('afterend',uncertainties);
 document.querySelector('#statements').previousElementSibling.lastElementChild.textContent='All figures in euros. The source register and decision table link to original evidence.';
 document.querySelector('#evidence').innerHTML=data.evidence.map(e=>`<div class="evidence-item"><b>${esc(e.id)}</b><a href="${sourceUrl(e.source)}" target="_blank" rel="noopener">${esc(e.source)}</a></div>`).join('');
 document.querySelector('#controls').innerHTML=data.boardRecommendation.immediateControls.map(c=>`<li>${esc(c)}</li>`).join('');
 function draw(){let q=document.querySelector('#search').value.trim().toLowerCase(),tier=document.querySelector('#tier').value;let rows=data.decisions.filter(d=>(tier==='all'||d.reviewTier===tier)&&(!q||`${d.id} ${d.question} ${d.answer}`.toLowerCase().includes(q)));document.querySelector('#count').textContent=`${rows.length} of 100`;document.querySelector('#decisions').innerHTML=rows.map(d=>`<tr><td>${esc(d.id)}${d.reviewTier==='material_judgment'?'<span class="material-mark">◆</span>':''}</td><td>${esc(d.question)}</td><td>${esc(d.answer)}</td><td>${evidenceText(d.evidence)}</td><td><span class="pill ${esc(d.confidence)}">${esc(d.confidence)}</span></td></tr>`).join('')}
 document.querySelector('#search').addEventListener('input',draw);document.querySelector('#tier').addEventListener('change',draw);draw();
}
function renderReview(data){let material=data.decisions.filter(d=>d.reviewTier==='material_judgment');document.querySelector('#overrides strong').textContent=material.filter(d=>d.changedFromAI).length;document.querySelector('#low-confidence strong').textContent=material.filter(d=>d.confidence==='low').length;
 function draw(){let q=document.querySelector('#search').value.trim().toLowerCase(),f=document.querySelector('#filter').value;let rows=material.filter(d=>(f==='all'||(f==='changed'&&d.changedFromAI)||(f==='low'&&d.confidence==='low'))&&(!q||`${d.id} ${d.question} ${d.answer}`.toLowerCase().includes(q)));document.querySelector('#count').textContent=`${rows.length} of 25`;document.querySelector('#review-list').innerHTML=rows.map(d=>{let changed=d.changedFromAI,low=d.confidence==='low';return `<article class="review-card"><div class="review-card-head"><div><p class="eyebrow">${esc(d.id)} · ${esc(d.category.replaceAll('_',' '))}</p><h2>${esc(d.question)}</h2></div><div class="badge-row">${changed?'<span class="badge">Changed from Agent 1</span>':''}${low?'<span class="badge warn">Low confidence</span>':''}</div></div><div class="review-columns"><div><b>Agent 1 proposal</b><p>${esc(d.firstAIProposal??d.aiProposal)}</p></div><div><b>Agent 2 position</b><p>${esc(d.agent2Position??d.independentChallenge)}</p></div><div><b>Recommended answer</b><p>${esc(d.answer)}</p></div></div><div class="review-detail"><div><b>Reasoning</b><p>${esc(d.studentReasoning)}</p></div><div class="review-meta"><b>Evidence & effect</b><p>${evidenceText(d.evidence)} · ${esc(d.confidence)} confidence</p><p>${Object.entries(d.statementEffect||{}).map(([k,v])=>`${title(k)} ${v===null?'—':signed(v)}`).join(' · ')}</p></div></div></article>`}).join('')}
 document.querySelector('#search').addEventListener('input',draw);document.querySelector('#filter').addEventListener('change',draw);draw()}
fetch('/data.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json()}).then(data=>{data.evidence.forEach(e=>evidenceCodes[e.id]=e.source);document.body.dataset.page==='review'?renderReview(data):renderHome(data)}).catch(e=>{document.querySelector('main').insertAdjacentHTML('afterbegin',`<p role="alert">The case data could not be loaded. ${esc(e.message)}</p>`)});
